# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/prj_ai_news',
                'doc_host': 'https://fbereilh.github.io',
                'git_url': 'https://github.com/fbereilh/prj_ai_news',
                'lib_path': 'prj_ai_news'},
  'syms': {'prj_ai_news.core': {'prj_ai_news.core.foo': ('core.html#foo', 'prj_ai_news/core.py')}}}
